### ISSUE TITLE
不过滤没有目标的图像

### ISSUE THREAD

**Issue by liliwannian** [zf020114/DARDet#4]
您好，我的数据集里面有些图片有目标，有些没有。现在我想把所有的数据都进行训练，请问该如何修改代码，才能不过滤空目标图片？希望您有空能回答一下，谢谢！

**Comment by zf020114** [comment]
你可以在Coco数据集文件里面把过滤空图像的那段代码删掉。或者你查询一下可能在Coco数据集文件里面有这个设置。路径mmdet/dataset/coco.py发自我的华为手机-------- 原始邮件 --------发件人： 面面 ***@***.***>日期： 2021年10月13日周三 中午11:35收件人： zf020114/DARDet ***@***.***>抄送： Subscribed ***@***.***>主    题： [zf020114/DARDet] 不过滤没有目标的图像 (#4)

您好，我的数据集里面有些图片有目标，有些没有。现在我想把所有的数据都进行训练，请问该如何修改代码，才能不过滤空目标图片？希望您有空能回答一下，谢谢！
