### ISSUE TITLE
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'

### ISSUE THREAD

**Issue by songhetian834764034** [zf020114/DARDet#6]
作者您好！感谢您对于工作的分享！在用您的模型跑DOTA数据集以及自定义数据集时报错：
  File "/home/song/anaconda3/envs/DARDet/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'
可能是数据加载的问题，我按照DOTA_devkit中的DOTA2COCO进行数据集格式的转换与加载。希望您有空可以解答一下，谢谢！

**Comment by G-Naughty** [comment]
您好，我也遇到了和您一样的问题，请问您解决了么？是如何解决的，期待您的答复，谢谢

**Comment by songhetian834764034** [comment]
> 您好，我也遇到了和您一样的问题，请问您解决了么？是如何解决的，期待您的答复，谢谢

对不起，没有解决Orz

**Comment by zf020114** [comment]
你好，请问是的运行生成JSON文件时候报错，还是在生成json文件后，模型训练的时候报错？

**Comment by songhetian834764034** [comment]
> 你好，请问是的运行生成JSON文件时候报错，还是在生成json文件后，模型训练的时候报错？

作者您好，我用相同的格式在其它模型上跑通了。这个问题是在模型训练的过程中出现，不太清楚是哪个部分报错。

**Comment by zf020114** [comment]
这样啊，我在训练的过程中，没有出现这样的问题，现在我也不清楚到底是哪里出了问题。我明天到学校了，先在自己的电脑上试好，马上更新代码。非常抱歉给你带来麻烦。

**Comment by G-Naughty** [comment]
Traceback (most recent call last):
  File "/home/hnu2/GGM/DARDet-master/tools/train.py", line 192, in <module>
    main()
  File "/home/hnu2/GGM/DARDet-master/tools/train.py", line 189, in main
    meta=meta)
  File "/home/hnu2/GGM/DARDet-master/mmdet/apis/train.py", line 175, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'


在训练时报的错，感觉是在训练读取batch数据时有问题。刚刚和redet上dota_devkit生成的json对比了，感觉没什么差别

**Comment by songhetian834764034** [comment]
> Traceback (most recent call last): File "/home/hnu2/GGM/DARDet-master/tools/train.py", line 192, in main() File "/home/hnu2/GGM/DARDet-master/tools/train.py", line 189, in main meta=meta) File "/home/hnu2/GGM/DARDet-master/mmdet/apis/train.py", line 175, in train_detector runner.run(data_loaders, cfg.workflow) File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run epoch_runner(data_loaders[i], **kwargs) File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train for i, data_batch in enumerate(self.data_loader): File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data return self._process_data(data) File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data data.reraise() File "/home/hnu2/.conda/envs/DARDet/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise raise self.exc_type(msg) TypeError: **init**() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'
> 
> 在训练时报的错，感觉是在训练读取batch数据时有问题。刚刚和redet上dota_devkit生成的json对比了，感觉没什么差别

应该不是格式处理的问题 等作者辛苦再更新一下吧

**Comment by zf020114** [comment]
已经更新

**Comment by G-Naughty** [comment]
您好，我依旧存在上述问题，想问一下您pycocotools是哪个版本的，我在调试时发现pycocotools的函数名称都有变动。

**Comment by zf020114** [comment]
Thank you very much for your interest in our work.
I think the problem comes from the file changes the API names for COCO in the coco.py file.
You can fix the bug by reinstall the mmdet compatible version of cocoAPI by
pip install -U "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
以上问题，我再次使用更新的程序在新的机器上编译，也没有出现这样的问题，要不你试试使用mmdetection提供的docker环境再次尝试一下。

**Comment by VV-DL-JUMP** [comment]
我也遇到了这个问题，调试发现这个是numpy报的错。需要将mmdet/core/mask/structures.py 中的第640和641行改为p[0::2] = p[0::2] * w_scale  ||||||   p[1::2] = p[1::2] * h_scale， 就可以解决了。

**Comment by VV-DL-JUMP** [comment]
需要参考的请前往https://gitee.com/vv_learnspace/dardet   mymodify分支，谢谢。
