### ISSUE TITLE
DOTA_DEVKIT

### ISSUE THREAD

**Issue by yzk-lab** [zf020114/DARDet#9]
作者你好，没有polyiou文件夹及csrc文件 这个DOTA_devkit的编译是怎么进行的？需要注意什么呢？

**Comment by zf020114** [comment]
我的使用说明Readme里面有安装说明。其实这个就是 dota数据集的官方代码，我是直接复制Redet网络里面的。发自我的华为手机-------- 原始邮件 --------发件人： yzk-lab ***@***.***>日期： 2021年11月13日周六 上午10:56收件人： zf020114/DARDet ***@***.***>抄送： Subscribed ***@***.***>主    题： [zf020114/DARDet] DOTA_DEVKIT (Issue #9)

作者你好，没有polyiou文件夹及csrc文件 这个DOTA_devkit的编译是怎么进行的？需要注意什么呢？
